// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: message.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_TypeInvalid  MessageType = 0
	MessageType_TypeKeygen1  MessageType = 1
	MessageType_TypeKeygen2  MessageType = 2
	MessageType_TypeKeygen3  MessageType = 3
	MessageType_TypeRefresh1 MessageType = 4
	MessageType_TypeRefresh2 MessageType = 5
	MessageType_TypeRefresh3 MessageType = 6
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "TypeInvalid",
		1: "TypeKeygen1",
		2: "TypeKeygen2",
		3: "TypeKeygen3",
		4: "TypeRefresh1",
		5: "TypeRefresh2",
		6: "TypeRefresh3",
	}
	MessageType_value = map[string]int32{
		"TypeInvalid":  0,
		"TypeKeygen1":  1,
		"TypeKeygen2":  2,
		"TypeKeygen3":  3,
		"TypeRefresh1": 4,
		"TypeRefresh2": 5,
		"TypeRefresh3": 6,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_message_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_message_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

type Broadcast int32

const (
	Broadcast_None     Broadcast = 0
	Broadcast_Basic    Broadcast = 1
	Broadcast_Reliable Broadcast = 2
)

// Enum value maps for Broadcast.
var (
	Broadcast_name = map[int32]string{
		0: "None",
		1: "Basic",
		2: "Reliable",
	}
	Broadcast_value = map[string]int32{
		"None":     0,
		"Basic":    1,
		"Reliable": 2,
	}
)

func (x Broadcast) Enum() *Broadcast {
	p := new(Broadcast)
	*p = x
	return p
}

func (x Broadcast) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Broadcast) Descriptor() protoreflect.EnumDescriptor {
	return file_message_proto_enumTypes[1].Descriptor()
}

func (Broadcast) Type() protoreflect.EnumType {
	return &file_message_proto_enumTypes[1]
}

func (x Broadcast) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Broadcast.Descriptor instead.
func (Broadcast) EnumDescriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{1}
}

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type      MessageType `protobuf:"varint,1,opt,name=type,proto3,enum=pb.MessageType" json:"type,omitempty"`
	From      string      `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To        string      `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Broadcast Broadcast   `protobuf:"varint,4,opt,name=broadcast,proto3,enum=pb.Broadcast" json:"broadcast,omitempty"`
	// Types that are assignable to Content:
	//	*Message_Keygen1
	//	*Message_Keygen2
	//	*Message_Keygen3
	//	*Message_Refresh1
	//	*Message_Refresh2
	//	*Message_Refresh3
	Content isMessage_Content `protobuf_oneof:"content"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_TypeInvalid
}

func (x *Message) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Message) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *Message) GetBroadcast() Broadcast {
	if x != nil {
		return x.Broadcast
	}
	return Broadcast_None
}

func (m *Message) GetContent() isMessage_Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (x *Message) GetKeygen1() *Keygen1 {
	if x, ok := x.GetContent().(*Message_Keygen1); ok {
		return x.Keygen1
	}
	return nil
}

func (x *Message) GetKeygen2() *Keygen2 {
	if x, ok := x.GetContent().(*Message_Keygen2); ok {
		return x.Keygen2
	}
	return nil
}

func (x *Message) GetKeygen3() *Keygen3 {
	if x, ok := x.GetContent().(*Message_Keygen3); ok {
		return x.Keygen3
	}
	return nil
}

func (x *Message) GetRefresh1() *Refresh1 {
	if x, ok := x.GetContent().(*Message_Refresh1); ok {
		return x.Refresh1
	}
	return nil
}

func (x *Message) GetRefresh2() *Refresh2 {
	if x, ok := x.GetContent().(*Message_Refresh2); ok {
		return x.Refresh2
	}
	return nil
}

func (x *Message) GetRefresh3() *Refresh3 {
	if x, ok := x.GetContent().(*Message_Refresh3); ok {
		return x.Refresh3
	}
	return nil
}

type isMessage_Content interface {
	isMessage_Content()
}

type Message_Keygen1 struct {
	Keygen1 *Keygen1 `protobuf:"bytes,11,opt,name=keygen1,proto3,oneof"`
}

type Message_Keygen2 struct {
	Keygen2 *Keygen2 `protobuf:"bytes,12,opt,name=keygen2,proto3,oneof"`
}

type Message_Keygen3 struct {
	Keygen3 *Keygen3 `protobuf:"bytes,13,opt,name=keygen3,proto3,oneof"`
}

type Message_Refresh1 struct {
	Refresh1 *Refresh1 `protobuf:"bytes,21,opt,name=refresh1,proto3,oneof"`
}

type Message_Refresh2 struct {
	Refresh2 *Refresh2 `protobuf:"bytes,22,opt,name=refresh2,proto3,oneof"`
}

type Message_Refresh3 struct {
	Refresh3 *Refresh3 `protobuf:"bytes,23,opt,name=refresh3,proto3,oneof"`
}

func (*Message_Keygen1) isMessage_Content() {}

func (*Message_Keygen2) isMessage_Content() {}

func (*Message_Keygen3) isMessage_Content() {}

func (*Message_Refresh1) isMessage_Content() {}

func (*Message_Refresh2) isMessage_Content() {}

func (*Message_Refresh3) isMessage_Content() {}

type Keygen1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash []byte `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (x *Keygen1) Reset() {
	*x = Keygen1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Keygen1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Keygen1) ProtoMessage() {}

func (x *Keygen1) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Keygen1.ProtoReflect.Descriptor instead.
func (*Keygen1) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{1}
}

func (x *Keygen1) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

type Keygen2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rid []byte `protobuf:"bytes,1,opt,name=rid,proto3" json:"rid,omitempty"`
	X   *Point `protobuf:"bytes,2,opt,name=X,proto3" json:"X,omitempty"`
	A   *Point `protobuf:"bytes,3,opt,name=A,proto3" json:"A,omitempty"`
	U   []byte `protobuf:"bytes,4,opt,name=u,proto3" json:"u,omitempty"`
}

func (x *Keygen2) Reset() {
	*x = Keygen2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Keygen2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Keygen2) ProtoMessage() {}

func (x *Keygen2) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Keygen2.ProtoReflect.Descriptor instead.
func (*Keygen2) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{2}
}

func (x *Keygen2) GetRid() []byte {
	if x != nil {
		return x.Rid
	}
	return nil
}

func (x *Keygen2) GetX() *Point {
	if x != nil {
		return x.X
	}
	return nil
}

func (x *Keygen2) GetA() *Point {
	if x != nil {
		return x.A
	}
	return nil
}

func (x *Keygen2) GetU() []byte {
	if x != nil {
		return x.U
	}
	return nil
}

type Keygen3 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SchX *Scalar `protobuf:"bytes,1,opt,name=schX,proto3" json:"schX,omitempty"`
}

func (x *Keygen3) Reset() {
	*x = Keygen3{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Keygen3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Keygen3) ProtoMessage() {}

func (x *Keygen3) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Keygen3.ProtoReflect.Descriptor instead.
func (*Keygen3) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{3}
}

func (x *Keygen3) GetSchX() *Scalar {
	if x != nil {
		return x.SchX
	}
	return nil
}

type Refresh1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash []byte `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (x *Refresh1) Reset() {
	*x = Refresh1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Refresh1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Refresh1) ProtoMessage() {}

func (x *Refresh1) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Refresh1.ProtoReflect.Descriptor instead.
func (*Refresh1) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{4}
}

func (x *Refresh1) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

type Refresh2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X   []*Point `protobuf:"bytes,1,rep,name=X,proto3" json:"X,omitempty"`
	A   []*Point `protobuf:"bytes,2,rep,name=A,proto3" json:"A,omitempty"`
	Y   *Point   `protobuf:"bytes,3,opt,name=Y,proto3" json:"Y,omitempty"`
	B   *Point   `protobuf:"bytes,4,opt,name=B,proto3" json:"B,omitempty"`
	N   *Int     `protobuf:"bytes,5,opt,name=N,proto3" json:"N,omitempty"`
	S   *Int     `protobuf:"bytes,6,opt,name=S,proto3" json:"S,omitempty"`
	T   *Int     `protobuf:"bytes,7,opt,name=T,proto3" json:"T,omitempty"`
	Rho []byte   `protobuf:"bytes,8,opt,name=rho,proto3" json:"rho,omitempty"`
	U   []byte   `protobuf:"bytes,9,opt,name=u,proto3" json:"u,omitempty"`
}

func (x *Refresh2) Reset() {
	*x = Refresh2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Refresh2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Refresh2) ProtoMessage() {}

func (x *Refresh2) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Refresh2.ProtoReflect.Descriptor instead.
func (*Refresh2) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{5}
}

func (x *Refresh2) GetX() []*Point {
	if x != nil {
		return x.X
	}
	return nil
}

func (x *Refresh2) GetA() []*Point {
	if x != nil {
		return x.A
	}
	return nil
}

func (x *Refresh2) GetY() *Point {
	if x != nil {
		return x.Y
	}
	return nil
}

func (x *Refresh2) GetB() *Point {
	if x != nil {
		return x.B
	}
	return nil
}

func (x *Refresh2) GetN() *Int {
	if x != nil {
		return x.N
	}
	return nil
}

func (x *Refresh2) GetS() *Int {
	if x != nil {
		return x.S
	}
	return nil
}

func (x *Refresh2) GetT() *Int {
	if x != nil {
		return x.T
	}
	return nil
}

func (x *Refresh2) GetRho() []byte {
	if x != nil {
		return x.Rho
	}
	return nil
}

func (x *Refresh2) GetU() []byte {
	if x != nil {
		return x.U
	}
	return nil
}

type Refresh3 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mod  *ZKMod      `protobuf:"bytes,1,opt,name=mod,proto3" json:"mod,omitempty"`
	Prm  *ZKPrm      `protobuf:"bytes,2,opt,name=prm,proto3" json:"prm,omitempty"`
	C    *Ciphertext `protobuf:"bytes,3,opt,name=c,proto3" json:"c,omitempty"`
	SchX []*Scalar   `protobuf:"bytes,4,rep,name=schX,proto3" json:"schX,omitempty"`
	SchY *Scalar     `protobuf:"bytes,5,opt,name=schY,proto3" json:"schY,omitempty"`
}

func (x *Refresh3) Reset() {
	*x = Refresh3{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Refresh3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Refresh3) ProtoMessage() {}

func (x *Refresh3) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Refresh3.ProtoReflect.Descriptor instead.
func (*Refresh3) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{6}
}

func (x *Refresh3) GetMod() *ZKMod {
	if x != nil {
		return x.Mod
	}
	return nil
}

func (x *Refresh3) GetPrm() *ZKPrm {
	if x != nil {
		return x.Prm
	}
	return nil
}

func (x *Refresh3) GetC() *Ciphertext {
	if x != nil {
		return x.C
	}
	return nil
}

func (x *Refresh3) GetSchX() []*Scalar {
	if x != nil {
		return x.SchX
	}
	return nil
}

func (x *Refresh3) GetSchY() *Scalar {
	if x != nil {
		return x.SchY
	}
	return nil
}

// Sign1 should actually be two messages, the first is broadcast and the second it p2p
type Sign1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ki    *Ciphertext `protobuf:"bytes,1,opt,name=Ki,proto3" json:"Ki,omitempty"`
	Gi    *Ciphertext `protobuf:"bytes,2,opt,name=Gi,proto3" json:"Gi,omitempty"`
	Zkenc *ZKEnc      `protobuf:"bytes,3,opt,name=zkenc,proto3" json:"zkenc,omitempty"`
}

func (x *Sign1) Reset() {
	*x = Sign1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sign1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sign1) ProtoMessage() {}

func (x *Sign1) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sign1.ProtoReflect.Descriptor instead.
func (*Sign1) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{7}
}

func (x *Sign1) GetKi() *Ciphertext {
	if x != nil {
		return x.Ki
	}
	return nil
}

func (x *Sign1) GetGi() *Ciphertext {
	if x != nil {
		return x.Gi
	}
	return nil
}

func (x *Sign1) GetZkenc() *ZKEnc {
	if x != nil {
		return x.Zkenc
	}
	return nil
}

var File_message_proto protoreflect.FileDescriptor

var file_message_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x02, 0x70, 0x62, 0x1a, 0x0b, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x08, 0x7a, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x89, 0x03, 0x0a, 0x07, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x23, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x66,
	0x72, 0x6f, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12,
	0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x74, 0x6f, 0x12,
	0x2b, 0x0a, 0x09, 0x62, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73,
	0x74, 0x52, 0x09, 0x62, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x07,
	0x6b, 0x65, 0x79, 0x67, 0x65, 0x6e, 0x31, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e,
	0x70, 0x62, 0x2e, 0x4b, 0x65, 0x79, 0x67, 0x65, 0x6e, 0x31, 0x48, 0x00, 0x52, 0x07, 0x6b, 0x65,
	0x79, 0x67, 0x65, 0x6e, 0x31, 0x12, 0x27, 0x0a, 0x07, 0x6b, 0x65, 0x79, 0x67, 0x65, 0x6e, 0x32,
	0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x4b, 0x65, 0x79, 0x67,
	0x65, 0x6e, 0x32, 0x48, 0x00, 0x52, 0x07, 0x6b, 0x65, 0x79, 0x67, 0x65, 0x6e, 0x32, 0x12, 0x27,
	0x0a, 0x07, 0x6b, 0x65, 0x79, 0x67, 0x65, 0x6e, 0x33, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x4b, 0x65, 0x79, 0x67, 0x65, 0x6e, 0x33, 0x48, 0x00, 0x52, 0x07,
	0x6b, 0x65, 0x79, 0x67, 0x65, 0x6e, 0x33, 0x12, 0x2a, 0x0a, 0x08, 0x72, 0x65, 0x66, 0x72, 0x65,
	0x73, 0x68, 0x31, 0x18, 0x15, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x52,
	0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x31, 0x48, 0x00, 0x52, 0x08, 0x72, 0x65, 0x66, 0x72, 0x65,
	0x73, 0x68, 0x31, 0x12, 0x2a, 0x0a, 0x08, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x32, 0x18,
	0x16, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x66, 0x72, 0x65,
	0x73, 0x68, 0x32, 0x48, 0x00, 0x52, 0x08, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x32, 0x12,
	0x2a, 0x0a, 0x08, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x33, 0x18, 0x17, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x33, 0x48,
	0x00, 0x52, 0x08, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x33, 0x42, 0x09, 0x0a, 0x07, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x1d, 0x0a, 0x07, 0x4b, 0x65, 0x79, 0x67, 0x65, 0x6e,
	0x31, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x04, 0x68, 0x61, 0x73, 0x68, 0x22, 0x5b, 0x0a, 0x07, 0x4b, 0x65, 0x79, 0x67, 0x65, 0x6e, 0x32,
	0x12, 0x10, 0x0a, 0x03, 0x72, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x72,
	0x69, 0x64, 0x12, 0x17, 0x0a, 0x01, 0x58, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e,
	0x70, 0x62, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x01, 0x58, 0x12, 0x17, 0x0a, 0x01, 0x41,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x6f, 0x69, 0x6e,
	0x74, 0x52, 0x01, 0x41, 0x12, 0x0c, 0x0a, 0x01, 0x75, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x01, 0x75, 0x22, 0x29, 0x0a, 0x07, 0x4b, 0x65, 0x79, 0x67, 0x65, 0x6e, 0x33, 0x12, 0x1e, 0x0a,
	0x04, 0x73, 0x63, 0x68, 0x58, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x62,
	0x2e, 0x53, 0x63, 0x61, 0x6c, 0x61, 0x72, 0x52, 0x04, 0x73, 0x63, 0x68, 0x58, 0x22, 0x1e, 0x0a,
	0x08, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x31, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73,
	0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x22, 0xd3, 0x01,
	0x0a, 0x08, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x32, 0x12, 0x17, 0x0a, 0x01, 0x58, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74,
	0x52, 0x01, 0x58, 0x12, 0x17, 0x0a, 0x01, 0x41, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09,
	0x2e, 0x70, 0x62, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x01, 0x41, 0x12, 0x17, 0x0a, 0x01,
	0x59, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x6f, 0x69,
	0x6e, 0x74, 0x52, 0x01, 0x59, 0x12, 0x17, 0x0a, 0x01, 0x42, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x01, 0x42, 0x12, 0x15,
	0x0a, 0x01, 0x4e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x70, 0x62, 0x2e, 0x49,
	0x6e, 0x74, 0x52, 0x01, 0x4e, 0x12, 0x15, 0x0a, 0x01, 0x53, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x07, 0x2e, 0x70, 0x62, 0x2e, 0x49, 0x6e, 0x74, 0x52, 0x01, 0x53, 0x12, 0x15, 0x0a, 0x01,
	0x54, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x70, 0x62, 0x2e, 0x49, 0x6e, 0x74,
	0x52, 0x01, 0x54, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x68, 0x6f, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x03, 0x72, 0x68, 0x6f, 0x12, 0x0c, 0x0a, 0x01, 0x75, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x01, 0x75, 0x22, 0xa2, 0x01, 0x0a, 0x08, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x33,
	0x12, 0x1b, 0x0a, 0x03, 0x6d, 0x6f, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e,
	0x70, 0x62, 0x2e, 0x5a, 0x4b, 0x4d, 0x6f, 0x64, 0x52, 0x03, 0x6d, 0x6f, 0x64, 0x12, 0x1b, 0x0a,
	0x03, 0x70, 0x72, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x70, 0x62, 0x2e,
	0x5a, 0x4b, 0x50, 0x72, 0x6d, 0x52, 0x03, 0x70, 0x72, 0x6d, 0x12, 0x1c, 0x0a, 0x01, 0x63, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x69, 0x70, 0x68, 0x65,
	0x72, 0x74, 0x65, 0x78, 0x74, 0x52, 0x01, 0x63, 0x12, 0x1e, 0x0a, 0x04, 0x73, 0x63, 0x68, 0x58,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x63, 0x61, 0x6c,
	0x61, 0x72, 0x52, 0x04, 0x73, 0x63, 0x68, 0x58, 0x12, 0x1e, 0x0a, 0x04, 0x73, 0x63, 0x68, 0x59,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x63, 0x61, 0x6c,
	0x61, 0x72, 0x52, 0x04, 0x73, 0x63, 0x68, 0x59, 0x22, 0x68, 0x0a, 0x05, 0x53, 0x69, 0x67, 0x6e,
	0x31, 0x12, 0x1e, 0x0a, 0x02, 0x4b, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x70, 0x62, 0x2e, 0x43, 0x69, 0x70, 0x68, 0x65, 0x72, 0x74, 0x65, 0x78, 0x74, 0x52, 0x02, 0x4b,
	0x69, 0x12, 0x1e, 0x0a, 0x02, 0x47, 0x69, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x70, 0x62, 0x2e, 0x43, 0x69, 0x70, 0x68, 0x65, 0x72, 0x74, 0x65, 0x78, 0x74, 0x52, 0x02, 0x47,
	0x69, 0x12, 0x1f, 0x0a, 0x05, 0x7a, 0x6b, 0x65, 0x6e, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x5a, 0x4b, 0x45, 0x6e, 0x63, 0x52, 0x05, 0x7a, 0x6b, 0x65,
	0x6e, 0x63, 0x2a, 0x87, 0x01, 0x0a, 0x0b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x54, 0x79, 0x70, 0x65, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69,
	0x64, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x54, 0x79, 0x70, 0x65, 0x4b, 0x65, 0x79, 0x67, 0x65,
	0x6e, 0x31, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x54, 0x79, 0x70, 0x65, 0x4b, 0x65, 0x79, 0x67,
	0x65, 0x6e, 0x32, 0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x54, 0x79, 0x70, 0x65, 0x4b, 0x65, 0x79,
	0x67, 0x65, 0x6e, 0x33, 0x10, 0x03, 0x12, 0x10, 0x0a, 0x0c, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65,
	0x66, 0x72, 0x65, 0x73, 0x68, 0x31, 0x10, 0x04, 0x12, 0x10, 0x0a, 0x0c, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x32, 0x10, 0x05, 0x12, 0x10, 0x0a, 0x0c, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x33, 0x10, 0x06, 0x2a, 0x2e, 0x0a, 0x09,
	0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x6f, 0x6e,
	0x65, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x42, 0x61, 0x73, 0x69, 0x63, 0x10, 0x01, 0x12, 0x0c,
	0x0a, 0x08, 0x52, 0x65, 0x6c, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x10, 0x02, 0x42, 0x25, 0x5a, 0x23,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x61, 0x75, 0x72, 0x75,
	0x73, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2f, 0x63, 0x6d, 0x70, 0x2d, 0x65, 0x63, 0x64, 0x73, 0x61,
	0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_message_proto_rawDescOnce sync.Once
	file_message_proto_rawDescData = file_message_proto_rawDesc
)

func file_message_proto_rawDescGZIP() []byte {
	file_message_proto_rawDescOnce.Do(func() {
		file_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_message_proto_rawDescData)
	})
	return file_message_proto_rawDescData
}

var file_message_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_message_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_message_proto_goTypes = []interface{}{
	(MessageType)(0),   // 0: pb.MessageType
	(Broadcast)(0),     // 1: pb.Broadcast
	(*Message)(nil),    // 2: pb.Message
	(*Keygen1)(nil),    // 3: pb.Keygen1
	(*Keygen2)(nil),    // 4: pb.Keygen2
	(*Keygen3)(nil),    // 5: pb.Keygen3
	(*Refresh1)(nil),   // 6: pb.Refresh1
	(*Refresh2)(nil),   // 7: pb.Refresh2
	(*Refresh3)(nil),   // 8: pb.Refresh3
	(*Sign1)(nil),      // 9: pb.Sign1
	(*Point)(nil),      // 10: pb.Point
	(*Scalar)(nil),     // 11: pb.Scalar
	(*Int)(nil),        // 12: pb.Int
	(*ZKMod)(nil),      // 13: pb.ZKMod
	(*ZKPrm)(nil),      // 14: pb.ZKPrm
	(*Ciphertext)(nil), // 15: pb.Ciphertext
	(*ZKEnc)(nil),      // 16: pb.ZKEnc
}
var file_message_proto_depIdxs = []int32{
	0,  // 0: pb.Message.type:type_name -> pb.MessageType
	1,  // 1: pb.Message.broadcast:type_name -> pb.Broadcast
	3,  // 2: pb.Message.keygen1:type_name -> pb.Keygen1
	4,  // 3: pb.Message.keygen2:type_name -> pb.Keygen2
	5,  // 4: pb.Message.keygen3:type_name -> pb.Keygen3
	6,  // 5: pb.Message.refresh1:type_name -> pb.Refresh1
	7,  // 6: pb.Message.refresh2:type_name -> pb.Refresh2
	8,  // 7: pb.Message.refresh3:type_name -> pb.Refresh3
	10, // 8: pb.Keygen2.X:type_name -> pb.Point
	10, // 9: pb.Keygen2.A:type_name -> pb.Point
	11, // 10: pb.Keygen3.schX:type_name -> pb.Scalar
	10, // 11: pb.Refresh2.X:type_name -> pb.Point
	10, // 12: pb.Refresh2.A:type_name -> pb.Point
	10, // 13: pb.Refresh2.Y:type_name -> pb.Point
	10, // 14: pb.Refresh2.B:type_name -> pb.Point
	12, // 15: pb.Refresh2.N:type_name -> pb.Int
	12, // 16: pb.Refresh2.S:type_name -> pb.Int
	12, // 17: pb.Refresh2.T:type_name -> pb.Int
	13, // 18: pb.Refresh3.mod:type_name -> pb.ZKMod
	14, // 19: pb.Refresh3.prm:type_name -> pb.ZKPrm
	15, // 20: pb.Refresh3.c:type_name -> pb.Ciphertext
	11, // 21: pb.Refresh3.schX:type_name -> pb.Scalar
	11, // 22: pb.Refresh3.schY:type_name -> pb.Scalar
	15, // 23: pb.Sign1.Ki:type_name -> pb.Ciphertext
	15, // 24: pb.Sign1.Gi:type_name -> pb.Ciphertext
	16, // 25: pb.Sign1.zkenc:type_name -> pb.ZKEnc
	26, // [26:26] is the sub-list for method output_type
	26, // [26:26] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_message_proto_init() }
func file_message_proto_init() {
	if File_message_proto != nil {
		return
	}
	file_types_proto_init()
	file_zk_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Keygen1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Keygen2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Keygen3); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Refresh1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Refresh2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Refresh3); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sign1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_message_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Message_Keygen1)(nil),
		(*Message_Keygen2)(nil),
		(*Message_Keygen3)(nil),
		(*Message_Refresh1)(nil),
		(*Message_Refresh2)(nil),
		(*Message_Refresh3)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_message_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_proto_goTypes,
		DependencyIndexes: file_message_proto_depIdxs,
		EnumInfos:         file_message_proto_enumTypes,
		MessageInfos:      file_message_proto_msgTypes,
	}.Build()
	File_message_proto = out.File
	file_message_proto_rawDesc = nil
	file_message_proto_goTypes = nil
	file_message_proto_depIdxs = nil
}
