// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.7
// source: zk.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ZKMod struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	W *Int   `protobuf:"bytes,1,opt,name=w,proto3" json:"w,omitempty"`
	X []*Int `protobuf:"bytes,2,rep,name=x,proto3" json:"x,omitempty"`
	A []bool `protobuf:"varint,3,rep,packed,name=a,proto3" json:"a,omitempty"`
	B []bool `protobuf:"varint,4,rep,packed,name=b,proto3" json:"b,omitempty"`
	Z []*Int `protobuf:"bytes,5,rep,name=z,proto3" json:"z,omitempty"`
}

func (x *ZKMod) Reset() {
	*x = ZKMod{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zk_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZKMod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZKMod) ProtoMessage() {}

func (x *ZKMod) ProtoReflect() protoreflect.Message {
	mi := &file_zk_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZKMod.ProtoReflect.Descriptor instead.
func (*ZKMod) Descriptor() ([]byte, []int) {
	return file_zk_proto_rawDescGZIP(), []int{0}
}

func (x *ZKMod) GetW() *Int {
	if x != nil {
		return x.W
	}
	return nil
}

func (x *ZKMod) GetX() []*Int {
	if x != nil {
		return x.X
	}
	return nil
}

func (x *ZKMod) GetA() []bool {
	if x != nil {
		return x.A
	}
	return nil
}

func (x *ZKMod) GetB() []bool {
	if x != nil {
		return x.B
	}
	return nil
}

func (x *ZKMod) GetZ() []*Int {
	if x != nil {
		return x.Z
	}
	return nil
}

type ZKPrm struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	A []*Int `protobuf:"bytes,1,rep,name=a,proto3" json:"a,omitempty"`
	Z []*Int `protobuf:"bytes,2,rep,name=z,proto3" json:"z,omitempty"`
}

func (x *ZKPrm) Reset() {
	*x = ZKPrm{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zk_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZKPrm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZKPrm) ProtoMessage() {}

func (x *ZKPrm) ProtoReflect() protoreflect.Message {
	mi := &file_zk_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZKPrm.ProtoReflect.Descriptor instead.
func (*ZKPrm) Descriptor() ([]byte, []int) {
	return file_zk_proto_rawDescGZIP(), []int{1}
}

func (x *ZKPrm) GetA() []*Int {
	if x != nil {
		return x.A
	}
	return nil
}

func (x *ZKPrm) GetZ() []*Int {
	if x != nil {
		return x.Z
	}
	return nil
}

var File_zk_proto protoreflect.FileDescriptor

var file_zk_proto_rawDesc = []byte{
	0x0a, 0x08, 0x7a, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x0b,
	0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x68, 0x0a, 0x05, 0x5a,
	0x4b, 0x4d, 0x6f, 0x64, 0x12, 0x15, 0x0a, 0x01, 0x77, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x07, 0x2e, 0x70, 0x62, 0x2e, 0x49, 0x6e, 0x74, 0x52, 0x01, 0x77, 0x12, 0x15, 0x0a, 0x01, 0x78,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x70, 0x62, 0x2e, 0x49, 0x6e, 0x74, 0x52,
	0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x61, 0x18, 0x03, 0x20, 0x03, 0x28, 0x08, 0x52, 0x01, 0x61,
	0x12, 0x0c, 0x0a, 0x01, 0x62, 0x18, 0x04, 0x20, 0x03, 0x28, 0x08, 0x52, 0x01, 0x62, 0x12, 0x15,
	0x0a, 0x01, 0x7a, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x70, 0x62, 0x2e, 0x49,
	0x6e, 0x74, 0x52, 0x01, 0x7a, 0x22, 0x35, 0x0a, 0x05, 0x5a, 0x4b, 0x50, 0x72, 0x6d, 0x12, 0x15,
	0x0a, 0x01, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x70, 0x62, 0x2e, 0x49,
	0x6e, 0x74, 0x52, 0x01, 0x61, 0x12, 0x15, 0x0a, 0x01, 0x7a, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x07, 0x2e, 0x70, 0x62, 0x2e, 0x49, 0x6e, 0x74, 0x52, 0x01, 0x7a, 0x42, 0x25, 0x5a, 0x23,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x61, 0x75, 0x72, 0x75,
	0x73, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2f, 0x63, 0x6d, 0x70, 0x2d, 0x65, 0x63, 0x64, 0x73, 0x61,
	0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_zk_proto_rawDescOnce sync.Once
	file_zk_proto_rawDescData = file_zk_proto_rawDesc
)

func file_zk_proto_rawDescGZIP() []byte {
	file_zk_proto_rawDescOnce.Do(func() {
		file_zk_proto_rawDescData = protoimpl.X.CompressGZIP(file_zk_proto_rawDescData)
	})
	return file_zk_proto_rawDescData
}

var file_zk_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_zk_proto_goTypes = []interface{}{
	(*ZKMod)(nil), // 0: pb.ZKMod
	(*ZKPrm)(nil), // 1: pb.ZKPrm
	(*Int)(nil),   // 2: pb.Int
}
var file_zk_proto_depIdxs = []int32{
	2, // 0: pb.ZKMod.w:type_name -> pb.Int
	2, // 1: pb.ZKMod.x:type_name -> pb.Int
	2, // 2: pb.ZKMod.z:type_name -> pb.Int
	2, // 3: pb.ZKPrm.a:type_name -> pb.Int
	2, // 4: pb.ZKPrm.z:type_name -> pb.Int
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_zk_proto_init() }
func file_zk_proto_init() {
	if File_zk_proto != nil {
		return
	}
	file_types_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_zk_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZKMod); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zk_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZKPrm); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_zk_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_zk_proto_goTypes,
		DependencyIndexes: file_zk_proto_depIdxs,
		MessageInfos:      file_zk_proto_msgTypes,
	}.Build()
	File_zk_proto = out.File
	file_zk_proto_rawDesc = nil
	file_zk_proto_goTypes = nil
	file_zk_proto_depIdxs = nil
}
