// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: protocols/cmp/sign/message.proto

package sign

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_taurusgroup_cmp_ecdsa_pkg_math_curve "github.com/taurusgroup/cmp-ecdsa/pkg/math/curve"
	paillier "github.com/taurusgroup/cmp-ecdsa/pkg/paillier"
	affg "github.com/taurusgroup/cmp-ecdsa/pkg/zk/affg"
	enc "github.com/taurusgroup/cmp-ecdsa/pkg/zk/enc"
	logstar "github.com/taurusgroup/cmp-ecdsa/pkg/zk/logstar"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Sign2 struct {
	ProofEnc *enc.Proof           `protobuf:"bytes,1,opt,name=ProofEnc,proto3" json:"ProofEnc,omitempty"`
	K        *paillier.Ciphertext `protobuf:"bytes,2,opt,name=K,proto3" json:"K,omitempty"`
	G        *paillier.Ciphertext `protobuf:"bytes,3,opt,name=G,proto3" json:"G,omitempty"`
}

func (m *Sign2) Reset()         { *m = Sign2{} }
func (m *Sign2) String() string { return proto.CompactTextString(m) }
func (*Sign2) ProtoMessage()    {}
func (*Sign2) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5871a8774d7c616, []int{0}
}
func (m *Sign2) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Sign2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *Sign2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sign2.Merge(m, src)
}
func (m *Sign2) XXX_Size() int {
	return m.Size()
}
func (m *Sign2) XXX_DiscardUnknown() {
	xxx_messageInfo_Sign2.DiscardUnknown(m)
}

var xxx_messageInfo_Sign2 proto.InternalMessageInfo

type MtAMessage struct {
	// Dij is Dᵢⱼ = (aⱼ ⊙ Bᵢ) ⊕ encᵢ(- βⱼᵢ, sⱼᵢ)
	Dij *paillier.Ciphertext `protobuf:"bytes,1,opt,name=Dij,proto3" json:"Dij,omitempty"`
	// Fij is Fᵢⱼ = encⱼ(βⱼᵢ, rⱼᵢ)
	Fij   *paillier.Ciphertext `protobuf:"bytes,2,opt,name=Fij,proto3" json:"Fij,omitempty"`
	Proof *affg.Proof          `protobuf:"bytes,3,opt,name=Proof,proto3" json:"Proof,omitempty"`
}

func (m *MtAMessage) Reset()         { *m = MtAMessage{} }
func (m *MtAMessage) String() string { return proto.CompactTextString(m) }
func (*MtAMessage) ProtoMessage()    {}
func (*MtAMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5871a8774d7c616, []int{1}
}
func (m *MtAMessage) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MtAMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *MtAMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MtAMessage.Merge(m, src)
}
func (m *MtAMessage) XXX_Size() int {
	return m.Size()
}
func (m *MtAMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_MtAMessage.DiscardUnknown(m)
}

var xxx_messageInfo_MtAMessage proto.InternalMessageInfo

type Sign3 struct {
	// EchoHash = Hash(ssid, K₁, G₁, …, Kₙ, Gₙ)
	EchoHash      []byte                                                 `protobuf:"bytes,1,opt,name=EchoHash,proto3" json:"EchoHash,omitempty"`
	BigGammaShare *github_com_taurusgroup_cmp_ecdsa_pkg_math_curve.Point `protobuf:"bytes,2,opt,name=BigGammaShare,proto3,customtype=github.com/taurusgroup/cmp-ecdsa/pkg/math/curve.Point" json:"BigGammaShare,omitempty"`
	DeltaMtA      *MtAMessage                                            `protobuf:"bytes,3,opt,name=DeltaMtA,proto3" json:"DeltaMtA,omitempty"`
	ChiMtA        *MtAMessage                                            `protobuf:"bytes,4,opt,name=ChiMtA,proto3" json:"ChiMtA,omitempty"`
	ProofLog      *logstar.Proof                                         `protobuf:"bytes,5,opt,name=ProofLog,proto3" json:"ProofLog,omitempty"`
}

func (m *Sign3) Reset()         { *m = Sign3{} }
func (m *Sign3) String() string { return proto.CompactTextString(m) }
func (*Sign3) ProtoMessage()    {}
func (*Sign3) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5871a8774d7c616, []int{2}
}
func (m *Sign3) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Sign3) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *Sign3) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sign3.Merge(m, src)
}
func (m *Sign3) XXX_Size() int {
	return m.Size()
}
func (m *Sign3) XXX_DiscardUnknown() {
	xxx_messageInfo_Sign3.DiscardUnknown(m)
}

var xxx_messageInfo_Sign3 proto.InternalMessageInfo

type Sign4 struct {
	DeltaShare    *github_com_taurusgroup_cmp_ecdsa_pkg_math_curve.Scalar `protobuf:"bytes,1,opt,name=DeltaShare,proto3,customtype=github.com/taurusgroup/cmp-ecdsa/pkg/math/curve.Scalar" json:"DeltaShare,omitempty"`
	BigDeltaShare *github_com_taurusgroup_cmp_ecdsa_pkg_math_curve.Point  `protobuf:"bytes,2,opt,name=BigDeltaShare,proto3,customtype=github.com/taurusgroup/cmp-ecdsa/pkg/math/curve.Point" json:"BigDeltaShare,omitempty"`
	ProofLog      *logstar.Proof                                          `protobuf:"bytes,3,opt,name=ProofLog,proto3" json:"ProofLog,omitempty"`
}

func (m *Sign4) Reset()         { *m = Sign4{} }
func (m *Sign4) String() string { return proto.CompactTextString(m) }
func (*Sign4) ProtoMessage()    {}
func (*Sign4) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5871a8774d7c616, []int{3}
}
func (m *Sign4) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Sign4) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *Sign4) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sign4.Merge(m, src)
}
func (m *Sign4) XXX_Size() int {
	return m.Size()
}
func (m *Sign4) XXX_DiscardUnknown() {
	xxx_messageInfo_Sign4.DiscardUnknown(m)
}

var xxx_messageInfo_Sign4 proto.InternalMessageInfo

type SignOutput struct {
	SigmaShare *github_com_taurusgroup_cmp_ecdsa_pkg_math_curve.Scalar `protobuf:"bytes,1,opt,name=SigmaShare,proto3,customtype=github.com/taurusgroup/cmp-ecdsa/pkg/math/curve.Scalar" json:"SigmaShare,omitempty"`
}

func (m *SignOutput) Reset()         { *m = SignOutput{} }
func (m *SignOutput) String() string { return proto.CompactTextString(m) }
func (*SignOutput) ProtoMessage()    {}
func (*SignOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5871a8774d7c616, []int{4}
}
func (m *SignOutput) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SignOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *SignOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignOutput.Merge(m, src)
}
func (m *SignOutput) XXX_Size() int {
	return m.Size()
}
func (m *SignOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_SignOutput.DiscardUnknown(m)
}

var xxx_messageInfo_SignOutput proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Sign2)(nil), "sign.Sign2")
	proto.RegisterType((*MtAMessage)(nil), "sign.MtAMessage")
	proto.RegisterType((*Sign3)(nil), "sign.Sign3")
	proto.RegisterType((*Sign4)(nil), "sign.Sign4")
	proto.RegisterType((*SignOutput)(nil), "sign.SignOutput")
}

func init() { proto.RegisterFile("protocols/cmp/sign/message.proto", fileDescriptor_d5871a8774d7c616) }

var fileDescriptor_d5871a8774d7c616 = []byte{
	// 539 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0x4f, 0x6b, 0xdb, 0x3e,
	0x18, 0x8e, 0x9b, 0xa4, 0x04, 0xfd, 0x52, 0xf8, 0x21, 0xca, 0x08, 0x61, 0x73, 0x4a, 0x06, 0x23,
	0x87, 0xd5, 0x82, 0x74, 0x1b, 0xac, 0xb7, 0xa6, 0xed, 0x32, 0x68, 0xc3, 0x82, 0x73, 0xeb, 0x65,
	0x28, 0x9a, 0x22, 0xab, 0xb1, 0x2d, 0x23, 0xcb, 0x63, 0xe4, 0xb2, 0xe3, 0x76, 0xec, 0x47, 0xd8,
	0xc7, 0xd9, 0xb1, 0xc7, 0xd2, 0x43, 0x19, 0xc9, 0x97, 0xd8, 0x71, 0x48, 0x56, 0x5c, 0x0f, 0xb6,
	0x6e, 0x83, 0x1e, 0xf2, 0x47, 0xef, 0xf3, 0xe8, 0x7d, 0x9f, 0xe7, 0x91, 0x10, 0xd8, 0x49, 0xa4,
	0x50, 0x82, 0x88, 0x30, 0x45, 0x24, 0x4a, 0x50, 0xca, 0x59, 0x8c, 0x22, 0x9a, 0xa6, 0x98, 0x51,
	0xcf, 0x40, 0xb0, 0xa6, 0x6b, 0xed, 0x5d, 0xc6, 0x55, 0x90, 0x4d, 0x3d, 0x22, 0x22, 0xc4, 0x04,
	0x13, 0xc8, 0x80, 0xd3, 0x6c, 0x66, 0x56, 0x66, 0x61, 0xfe, 0xe5, 0x9b, 0xda, 0x8f, 0x92, 0x39,
	0x43, 0x09, 0xe6, 0x61, 0xc8, 0xa9, 0x44, 0x84, 0x27, 0x01, 0x95, 0x8a, 0x7e, 0x50, 0x16, 0xde,
	0xd6, 0xf0, 0x62, 0x8e, 0x68, 0x4c, 0xf4, 0xc7, 0x56, 0x1f, 0xd8, 0x2a, 0x9e, 0xcd, 0x98, 0xf9,
	0xb2, 0xf5, 0x87, 0xb6, 0x1e, 0x0a, 0x96, 0x2a, 0x2c, 0xd7, 0xbf, 0x39, 0xda, 0xfd, 0x08, 0xea,
	0x13, 0xce, 0xe2, 0x3e, 0xec, 0x81, 0xc6, 0x58, 0x0a, 0x31, 0x3b, 0x8e, 0x49, 0xcb, 0xd9, 0x71,
	0x7a, 0xff, 0xf5, 0x9b, 0xde, 0x62, 0xae, 0xdb, 0x9b, 0xb2, 0x5f, 0xa0, 0xb0, 0x0b, 0x9c, 0x93,
	0xd6, 0x86, 0xa1, 0x6c, 0x7b, 0x6b, 0x95, 0xde, 0x61, 0xa1, 0xd2, 0x77, 0x4e, 0x34, 0x67, 0xd8,
	0xaa, 0xde, 0xc5, 0x19, 0xee, 0xd7, 0x3e, 0x7f, 0xe9, 0x54, 0xba, 0x9f, 0x1c, 0x00, 0x46, 0xea,
	0x60, 0x94, 0xa7, 0x06, 0x9f, 0x80, 0xea, 0x11, 0x3f, 0xb7, 0x0a, 0x7e, 0xbd, 0x55, 0x13, 0x34,
	0xef, 0x15, 0x3f, 0xbf, 0x53, 0x86, 0x26, 0xc0, 0xc7, 0xa0, 0x6e, 0x84, 0x5b, 0x31, 0x5b, 0xde,
	0x62, 0x6e, 0xb2, 0xc9, 0x4d, 0xe5, 0x98, 0x55, 0x72, 0xb1, 0x91, 0x67, 0xb1, 0x07, 0xdb, 0xa0,
	0x71, 0x4c, 0x02, 0xf1, 0x1a, 0xa7, 0x81, 0x51, 0xd2, 0xf4, 0x8b, 0x35, 0x7c, 0x0b, 0xb6, 0x06,
	0x9c, 0x0d, 0x71, 0x14, 0xe1, 0x49, 0x80, 0x25, 0x35, 0x12, 0x9a, 0x83, 0x97, 0xd7, 0x37, 0x9d,
	0xe7, 0xa5, 0x53, 0x56, 0x38, 0x93, 0x59, 0xca, 0xa4, 0xc8, 0x12, 0x7d, 0x35, 0x76, 0x29, 0x79,
	0x97, 0x62, 0xa4, 0x8f, 0x22, 0xc2, 0x2a, 0x40, 0x24, 0x93, 0xef, 0xa9, 0x37, 0x16, 0x3c, 0x56,
	0xfe, 0xcf, 0xfd, 0xe0, 0x53, 0xd0, 0x38, 0xa2, 0xa1, 0xc2, 0x23, 0x75, 0x60, 0x45, 0xff, 0xef,
	0xe9, 0x4b, 0xe4, 0xdd, 0xa6, 0xe4, 0x17, 0x0c, 0xd8, 0x03, 0x9b, 0x87, 0x01, 0xd7, 0xdc, 0xda,
	0x6f, 0xb8, 0x16, 0xd7, 0x7d, 0x8d, 0xdb, 0x53, 0xc1, 0x5a, 0x75, 0xcb, 0x5d, 0xcc, 0xd7, 0xb7,
	0xa1, 0x7c, 0xc8, 0xa7, 0x82, 0xd9, 0x48, 0xbe, 0x3b, 0x79, 0x24, 0xcf, 0xe0, 0x19, 0x00, 0x66,
	0x66, 0xee, 0xd9, 0x84, 0x32, 0xd8, 0xbf, 0xbe, 0xe9, 0xbc, 0xf8, 0x57, 0xcf, 0x13, 0x82, 0x43,
	0x2c, 0xfd, 0x52, 0x37, 0x1b, 0x69, 0xa9, 0xfd, 0xbd, 0x44, 0x5a, 0x1a, 0x50, 0xb6, 0x5e, 0xfd,
	0x4b, 0xeb, 0x31, 0x00, 0xda, 0xf9, 0x9b, 0x4c, 0x25, 0x99, 0xd2, 0xf6, 0x27, 0x9c, 0x45, 0xf7,
	0x67, 0xff, 0xb6, 0x5b, 0x3e, 0x6f, 0x30, 0xfe, 0xba, 0x74, 0x9d, 0xcb, 0xa5, 0xeb, 0x5c, 0x2d,
	0x5d, 0xe7, 0xdb, 0xd2, 0x75, 0x2e, 0x56, 0x6e, 0xe5, 0x72, 0xe5, 0x56, 0xae, 0x56, 0x6e, 0xe5,
	0xac, 0xff, 0xe7, 0x39, 0xf6, 0x25, 0x2a, 0x1e, 0xa2, 0xe9, 0xa6, 0x29, 0xed, 0xfd, 0x08, 0x00,
	0x00, 0xff, 0xff, 0xe1, 0x95, 0x32, 0x7f, 0xa5, 0x04, 0x00, 0x00,
}

func (m *Sign2) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Sign2) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Sign2) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.G != nil {
		{
			size, err := m.G.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMessage(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.K != nil {
		{
			size, err := m.K.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMessage(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.ProofEnc != nil {
		{
			size, err := m.ProofEnc.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMessage(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MtAMessage) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MtAMessage) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MtAMessage) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Proof != nil {
		{
			size, err := m.Proof.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMessage(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.Fij != nil {
		{
			size, err := m.Fij.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMessage(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.Dij != nil {
		{
			size, err := m.Dij.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMessage(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Sign3) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Sign3) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Sign3) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ProofLog != nil {
		{
			size, err := m.ProofLog.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMessage(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	if m.ChiMtA != nil {
		{
			size, err := m.ChiMtA.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMessage(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if m.DeltaMtA != nil {
		{
			size, err := m.DeltaMtA.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMessage(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.BigGammaShare != nil {
		{
			size := m.BigGammaShare.Size()
			i -= size
			if _, err := m.BigGammaShare.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
			i = encodeVarintMessage(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.EchoHash) > 0 {
		i -= len(m.EchoHash)
		copy(dAtA[i:], m.EchoHash)
		i = encodeVarintMessage(dAtA, i, uint64(len(m.EchoHash)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Sign4) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Sign4) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Sign4) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ProofLog != nil {
		{
			size, err := m.ProofLog.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMessage(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.BigDeltaShare != nil {
		{
			size := m.BigDeltaShare.Size()
			i -= size
			if _, err := m.BigDeltaShare.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
			i = encodeVarintMessage(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.DeltaShare != nil {
		{
			size := m.DeltaShare.Size()
			i -= size
			if _, err := m.DeltaShare.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
			i = encodeVarintMessage(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *SignOutput) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SignOutput) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SignOutput) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.SigmaShare != nil {
		{
			size := m.SigmaShare.Size()
			i -= size
			if _, err := m.SigmaShare.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
			i = encodeVarintMessage(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintMessage(dAtA []byte, offset int, v uint64) int {
	offset -= sovMessage(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Sign2) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ProofEnc != nil {
		l = m.ProofEnc.Size()
		n += 1 + l + sovMessage(uint64(l))
	}
	if m.K != nil {
		l = m.K.Size()
		n += 1 + l + sovMessage(uint64(l))
	}
	if m.G != nil {
		l = m.G.Size()
		n += 1 + l + sovMessage(uint64(l))
	}
	return n
}

func (m *MtAMessage) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Dij != nil {
		l = m.Dij.Size()
		n += 1 + l + sovMessage(uint64(l))
	}
	if m.Fij != nil {
		l = m.Fij.Size()
		n += 1 + l + sovMessage(uint64(l))
	}
	if m.Proof != nil {
		l = m.Proof.Size()
		n += 1 + l + sovMessage(uint64(l))
	}
	return n
}

func (m *Sign3) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.EchoHash)
	if l > 0 {
		n += 1 + l + sovMessage(uint64(l))
	}
	if m.BigGammaShare != nil {
		l = m.BigGammaShare.Size()
		n += 1 + l + sovMessage(uint64(l))
	}
	if m.DeltaMtA != nil {
		l = m.DeltaMtA.Size()
		n += 1 + l + sovMessage(uint64(l))
	}
	if m.ChiMtA != nil {
		l = m.ChiMtA.Size()
		n += 1 + l + sovMessage(uint64(l))
	}
	if m.ProofLog != nil {
		l = m.ProofLog.Size()
		n += 1 + l + sovMessage(uint64(l))
	}
	return n
}

func (m *Sign4) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.DeltaShare != nil {
		l = m.DeltaShare.Size()
		n += 1 + l + sovMessage(uint64(l))
	}
	if m.BigDeltaShare != nil {
		l = m.BigDeltaShare.Size()
		n += 1 + l + sovMessage(uint64(l))
	}
	if m.ProofLog != nil {
		l = m.ProofLog.Size()
		n += 1 + l + sovMessage(uint64(l))
	}
	return n
}

func (m *SignOutput) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SigmaShare != nil {
		l = m.SigmaShare.Size()
		n += 1 + l + sovMessage(uint64(l))
	}
	return n
}

func sovMessage(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMessage(x uint64) (n int) {
	return sovMessage(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Sign2) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMessage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Sign2: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Sign2: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProofEnc", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ProofEnc == nil {
				m.ProofEnc = &enc.Proof{}
			}
			if err := m.ProofEnc.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field K", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.K == nil {
				m.K = &paillier.Ciphertext{}
			}
			if err := m.K.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field G", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.G == nil {
				m.G = &paillier.Ciphertext{}
			}
			if err := m.G.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMessage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMessage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MtAMessage) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMessage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MtAMessage: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MtAMessage: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Dij", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Dij == nil {
				m.Dij = &paillier.Ciphertext{}
			}
			if err := m.Dij.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Fij", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Fij == nil {
				m.Fij = &paillier.Ciphertext{}
			}
			if err := m.Fij.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Proof", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Proof == nil {
				m.Proof = &affg.Proof{}
			}
			if err := m.Proof.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMessage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMessage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Sign3) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMessage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Sign3: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Sign3: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EchoHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EchoHash = append(m.EchoHash[:0], dAtA[iNdEx:postIndex]...)
			if m.EchoHash == nil {
				m.EchoHash = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BigGammaShare", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v github_com_taurusgroup_cmp_ecdsa_pkg_math_curve.Point
			m.BigGammaShare = &v
			if err := m.BigGammaShare.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeltaMtA", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.DeltaMtA == nil {
				m.DeltaMtA = &MtAMessage{}
			}
			if err := m.DeltaMtA.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChiMtA", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ChiMtA == nil {
				m.ChiMtA = &MtAMessage{}
			}
			if err := m.ChiMtA.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProofLog", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ProofLog == nil {
				m.ProofLog = &logstar.Proof{}
			}
			if err := m.ProofLog.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMessage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMessage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Sign4) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMessage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Sign4: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Sign4: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeltaShare", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v github_com_taurusgroup_cmp_ecdsa_pkg_math_curve.Scalar
			m.DeltaShare = &v
			if err := m.DeltaShare.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BigDeltaShare", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v github_com_taurusgroup_cmp_ecdsa_pkg_math_curve.Point
			m.BigDeltaShare = &v
			if err := m.BigDeltaShare.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProofLog", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ProofLog == nil {
				m.ProofLog = &logstar.Proof{}
			}
			if err := m.ProofLog.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMessage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMessage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SignOutput) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMessage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SignOutput: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SignOutput: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SigmaShare", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v github_com_taurusgroup_cmp_ecdsa_pkg_math_curve.Scalar
			m.SigmaShare = &v
			if err := m.SigmaShare.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMessage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMessage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMessage(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMessage
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMessage
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMessage
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMessage
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMessage        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMessage          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMessage = fmt.Errorf("proto: unexpected end of group")
)
